config/routes.rb
Rails.application.routes.draw do
  # get 'addresses/index'
  resources :addresses
  root 'addresses#index'
end

app/models/address.rb
class Address < ActiveRecord::Base
	belongs_to :group
	#add field validations
	validates :name, :email, :phone, presence: true

	#paper_clip_code_from github homepage
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/ 
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :addresses
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :find_address, only: [:edit, :update, :destroy]

  def index
    if params[:group_id]
      @group = Group.find(params[:group_id])
      @addresses = @group.addresses.paginate(page: params[:page], per_page: 10)
    else
      @addresses = Address.paginate(page: params[:page], per_page: 10)
    end 
  end

  def new
  	@address = Address.new
  end

  def create
  	@address = Address.new(address_params)
  	if @address.save
  		flash[:success] = "Successfully created new contact"
  		redirect_to addresses_path
  	else
  		render 'new'
  	end
  end
  
  def edit
    # @address = Address.find(params[:id])
    # debugger
  end	

  def update
    # @address = Address.find(params[:id])
    if @address.update(address_params)
      flash[:success] = "Successfully updated the contact deatils"
      redirect_to addresses_path
    else
      render 'edit'
    end
  end

  def destroy
    # @address = Address.find(params[:id])
    @address.destroy
    flash[:success] = "Successfully deleted contact"
    redirect_to addresses_path
  end
      

  private 

  def find_address
    @address = Address.find(params[:id])
  end

  def address_params
  	params.require(:address).permit(:name, :email, :company, :address, :phone, :avatar, :group_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/addresses/_form.html.erb
<%= form_for @address, html: { multipart: true} do |f| %>           
    <div class="panel-body">
        <% if @address.errors.any? %>
          <div class="alert alert-danger">
              <h4>Please correct the following errors:</h4>
              <ul>
                <% @address.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
          </div>
        <% end %>

      <div class="form-horizontal">
        <div class="row">
          <div class="col-md-8">

            <div class="form-group">
              <!-- <label for="company" class="control-label col-md-3">Company</label>
              <div class="col-md-8">
                <input type="text" name="company" id="company" class="form-control">
              </div> -->
              <%= f.label :name, class: "control-label col-md-3" %>               
              <div class="col-md-8">
                <%= f.text_field :name, class: "form-control" %>                
              </div>
            </div>

            <div class="form-group">
              <%= f.label :company, class: "control-label col-md-3" %>               
              <div class="col-md-8">
                <%= f.text_field :company, class: "form-control" %>                
              </div>
            </div>

            <div class="form-group">
              <%= f.label :email, class: "control-label col-md-3" %>               
              <div class="col-md-8">
                <%= f.text_field :email, class: "form-control" %>                
              </div>
            </div>

            <div class="form-group">
              <%= f.label :phone, class: "control-label col-md-3" %>               
              <div class="col-md-8">
                <%= f.text_field :phone, class: "form-control" %>                
              </div>
            </div>
            <div class="form-group">
              <%= f.label :address, class: "control-label col-md-3" %>               
              <div class="col-md-8">
                <%= f.text_area :address, class: "form-control" %>                
              </div>
            </div>
            <div class="form-group">
              <label for="group" class="control-label col-md-3">Group</label>
              <div class="col-md-5">
                <%= f.collection_select :group_id, Group.all, :id, :name, { prompt: "Select Group"}, class: "form-control" %>


              </div>
              <div class="col-md-3">
                <a href="#" id="add-group-btn" class="btn btn-default btn-block">Add Group</a>
              </div>
            </div>
            <div class="form-group" id="add-new-group" style="display: none;">
              <div class="col-md-offset-3 col-md-8">
                <div class="input-group">
                  <input type="text" name="new_group" id="new_group" class="form-control">
                  <span class="input-group-btn">
                    <a href="#" class="btn btn-default">
                      <i class="glyphicon glyphicon-ok"></i>
                    </a>
                  </span>
                </div>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="fileinput fileinput-new" data-provides="fileinput">
              <div class="fileinput-new thumbnail" style="width: 200px; height: 200px;">
                <!-- <img src="http://placehold.it/150x150" alt="Photo"> -->
                <%= image_tag @address.avatar.url(:medium) %>
              </div>
              <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;"></div>
              <div class="text-center">
                <span class="btn btn-default btn-file"><span class="fileinput-new">Choose Photo</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span></span>
                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="panel-footer">
      <div class="row">
        <div class="col-md-8">
          <div class="row">
            <div class="col-md-offset-3 col-md-6">
              <button type="submit" class="btn btn-primary">Save</button>

              <%= link_to "Cancel", addresses_path, class: "btn btn-default" %>
              <!-- <a href="#" class="btn btn-default">Cancel</a> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/addresses/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Edit Contact</strong>
  </div>
    <%= render 'form' %>
</div>

app/views/addresses/index.html.erb
          <div class="panel panel-default">
            <table class="table">

            <% @addresses.each do |address| %>


              <tr>
                <td class="middle">
                  <div class="media">
                    <div class="media-left">
                      <a href="#">
                        <%= image_tag address.avatar.url(:thumb), class: "media-object", style: "width: 100px;height: 100px;"%>
                        <!-- <img class="media-object" src="http://placehold.it/100x100" alt="..."> -->
                      </a>
                    </div>
                    <div class="media-body">
                      <h4 class="media-heading"><%= address.name %></h4>
                      <address>
                        <strong><%= address.company %></strong><br>
                        <%= address.email %>
                      </address>
                    </div>
                  </div>
                </td>
                <td width="100" class="middle">
                  <div>
                    <!-- edit button in index -->
                    <%= link_to edit_address_path(address), class: "btn btn-circle btn-default btn-xs", title:"Edit" do %> 
                      <i class="glyphicon glyphicon-edit"></i>
                    <% end %>
                    <!-- delete button in index -->
                    <%= link_to address_path(address), :method => :delete, class: "btn btn-circle btn-danger btn-xs", title:"Delete", data: {confirm: "Are you sure ?"} do %> 
                      <i class="glyphicon glyphicon-remove"></i>
                    <% end %>
                  </div>
                </td>
              </tr>

            <% end %>
              <tr>
            </table>            
          </div>

          <div class="text-center">
            <%= will_paginate %>
           <!--  <nav>
              <ul class="pagination">
                <li>
                  <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li>
                  <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                  </a>
                </li>
              </ul>
            </nav> -->
          </div>

app/views/addresses/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <strong>Add Contact</strong>
  </div>
    <%= render 'form' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Addressbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to "Personal Address book", root_path, class: "navbar-brand text-uppercase" %>
          <!-- <a class="navbar-brand text-uppercase" href="#">            
            Personal Address book
          </a> -->
        </div>
        <!-- /.navbar-header -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <div class="nav navbar-right navbar-btn">

            <%= link_to new_address_path, class: "btn btn-success" do %>
              <i class="glyphicon glyphicon-plus"></i> 
              Add New Contact
            <% end %>

          </div>
        </div>
      </div>
    </nav>

 <!-- content -->
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <div class="list-group">
            <!-- set active links -->
            <% active = params[:group_id] == nil ? 'active' : '' %>
            <%= link_to addresses_path, class: "list-group-item #{active}" do %>
                  All Contacts <span class="badge"><%= Address.count %></span>
            <% end %>

            <% Group.all.each do |group| %>
              <% active = params[:group_id].to_i == group.id ? 'active' : '' %>
              <%= link_to addresses_path(group_id: group.id), class: "list-group-item #{active}" do %>
                  <%= group.name %> <span class="badge"><%= group.addresses.count %></span>
              <% end %>
            <% end %>            

          </div>
        </div><!-- /.col-md-3 -->

        <div class="col-md-9">
          <% flash.each do |type, message| %>
            <%= content_tag :div, class: "alert alert-#{type} alert-dismissible", role: "alert" do %>
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= message %>
            <% end %>
          <% end %>

          <%= yield %>

        </div>
      </div>
    </div>

</body>
</html>